- Status:
    - Maintenance:
        - Cleanuparr:
            icon: mdi-delete-sweep
            href: http://localhost:11011/
            description: Queue cleaner

        - FileFlows:
            icon: mdi-file-video
            href: http://localhost:19200/
            description: Video processing
            widget:
              type: fileflows
              url: http://fileflows:5000

    - Calendar:
        - Release Schedule:
            icon: mdi-calendar
            widget:
              type: calendar
              view: agenda
              maxEvents: 15
              maxDays: 30
              previousDays: 3
              showTime: true
              showDetails: true
              integrations:
                - type: sonarr
                  service_group: Media
                  service_name: Sonarr
                  color: sky
                - type: radarr
                  service_group: Media
                  service_name: Radarr
                  color: orange
