- Media:
     - Radarr:
         icon: radarr.png
         href: http://localhost/radarr/
         description: Movie management
         widget:
           type: radarr
           url: http://radarr:7878
           key: {{HOMEPAGE_VAR_RADARR_API_KEY}}

     - Sonarr:
         icon: sonarr.png
         href: http://localhost/sonarr/
         description: Series management
         widget:
           type: sonarr
           url: http://sonarr:8989
           key: {{HOMEPAGE_VAR_SONARR_API_KEY}}

     - Prowlarr:
         icon: prowlarr.png
         href: http://localhost/prowlarr/
         description: Indexer manager
         widget:
           type: prowlarr
           url: http://prowlarr:9696
           key: {{HOMEPAGE_VAR_PROWLARR_API_KEY}}

     - Bazarr:
         icon: bazarr.png
         href: http://localhost/bazarr/
         description: Subtitle management
         widget:
           type: bazarr
           url: http://bazarr:6767/bazarr
           key: {{HOMEPAGE_VAR_BAZARR_API_KEY}}
    
     - Jellyfin:
         icon: jellyfin.png
         href: http://localhost/jellyfin/
         description: Jellyfin Media Server
         widget:
           type: jellyfin
           url: http://jellyfin:8096
           key: {{HOMEPAGE_VAR_JELLYFIN_API_KEY}}

     - Jellyseerr:
         icon: jellyseerr.png
         href: http://jellyseerr.localhost/
         description: Media request manager
         widget:
           type: jellyseerr
           url: http://jellyseerr:5055
           key: {{HOMEPAGE_VAR_JELLYSEERR_API_KEY}}

     - qBittorrent:
         icon: qbittorrent.png
         href: http://localhost/qbittorrent/
         description: Torrent client
         widget:
           type: qbittorrent
           url: http://qbittorrent:8080
           username: {{HOMEPAGE_VAR_QBITTORRENT_USER}}
           password: {{HOMEPAGE_VAR_QBITTORRENT_PASS}}

     - SABnzbd:
         icon: sabnzbd.png
         href: http://localhost/sabnzbd/
         description: Usenet downloader
         widget:
           type: sabnzbd
           url: http://sabnzbd:8080
           key: {{HOMEPAGE_VAR_SABNZBD_API_KEY}}

     - Jellystat:
         icon: jellystat.png
         href: http://jellystat.localhost/
         description: Media statistics
         widget:
           type: jellystat
           url: http://jellystat:3000
           key: {{HOMEPAGE_VAR_JELLYSTAT_API_KEY}}
           days: 30 # optional, defaults to 30
- Status:
    - Maintenance:
        - Cleanuparr:
            icon: mdi-delete-sweep
            href: http://localhost:11011/
            description: Queue cleaner

        - FileFlows:
            icon: mdi-file-video
            href: http://localhost:19200/
            description: Video processing
            widget:
              type: fileflows
              url: http://fileflows:5000

    - Calendar:
        - Release Schedule:
            icon: mdi-calendar
            widget:
              type: calendar
              view: agenda
              maxEvents: 15
              maxDays: 30
              previousDays: 3
              showTime: true
              showDetails: true
              integrations:
                - type: sonarr
                  service_group: Media
                  service_name: Sonarr
                  color: sky
                - type: radarr
                  service_group: Media
                  service_name: Radarr
                  color: orange

- Monitoring:
    - Beszel:
        icon: beszel.png
        href: http://beszel.localhost/
        description: Lightweight server monitoring
        widget:
          type: beszel
          url: http://beszel:8090
          username: {{HOMEPAGE_VAR_BESZEL_USER}}
          password: {{HOMEPAGE_VAR_BESZEL_PASS}}
          systemId: ibcojulxpoa6st3
          version: 2

    - Netdata:
        icon: netdata.png
        href: http://localhost:19999/
        description: Real-time performance monitoring
        widget:
          type: netdata
          url: http://netdata:19999

- Docker:
    - Containers:
        icon: docker.png
        description: Container management
