services:
  postgresql:
    image: postgres:16
    container_name: commafeed-db
    restart: unless-stopped
    mem_limit: 256m
    environment:
      POSTGRES_USER: commafeed
      POSTGRES_PASSWORD: commafeed
      POSTGRES_DB: commafeed
    volumes:
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "commafeed", "-U", "commafeed"]
      timeout: 10s
      interval: 5s
      retries: 5
    networks:
      - servarrnetwork

  commafeed:
    image: athou/commafeed:latest-postgresql
    container_name: commafeed
    restart: unless-stopped
    mem_limit: 256m
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgresql:5432/commafeed
      - QUARKUS_DATASOURCE_USERNAME=commafeed
      - QUARKUS_DATASOURCE_PASSWORD=commafeed
    volumes:
      - ./data/commafeed:/commafeed/data
    ports:
      - "8082:8082"
    healthcheck:
      test: ["CMD-SHELL", "[ -f /proc/1/cmdline ] && exit 0 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - servarrnetwork

networks:
  servarrnetwork:
    external: true
